# Generated by Django 3.0.3 on 2020-03-02 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StepikUser',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('avatar', models.CharField(max_length=500, verbose_name='Аватар')),
                ('level_title', models.CharField(max_length=255, verbose_name='Уровень')),
                ('knowledge', models.PositiveIntegerField(default=0, verbose_name='Уровень знаний')),
                ('reputation', models.PositiveIntegerField(default=0, verbose_name='Уровень репутации')),
                ('solved_steps_count', models.PositiveIntegerField(default=0, verbose_name='Пройдено степов')),
                ('issued_certificates_count', models.PositiveIntegerField(default=0, verbose_name='Получено сертификатов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
            ],
            options={
                'verbose_name': 'Автор комментария',
                'verbose_name_plural': 'Авторы комментариев',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор')),
                ('user_role', models.CharField(default='student', max_length=50, verbose_name='Роль комментатора')),
                ('created_on_stepik', models.DateTimeField(verbose_name='Дата и время создания комментария на платформе')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('epic_count', models.PositiveIntegerField(default=0, verbose_name='Количество лайков за комментарий')),
                ('abuse_count', models.PositiveIntegerField(default=0, verbose_name='Количество дизлайков за комментарий')),
                ('target', models.PositiveIntegerField(default=0, verbose_name='Идентификатор степа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Comment', verbose_name='Родительский комментарий')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.StepikUser', verbose_name='Автор комментария')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
    ]
