# Generated by Django 3.0.3 on 2020-03-02 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_on_stepik',
        ),
    ]
