# Generated by Django 3.0.3 on 2020-05-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.PositiveIntegerField(default=0, verbose_name='Идентификатор курса')),
                ('section_id', models.PositiveIntegerField(default=0, verbose_name='Идентификатор раздела')),
                ('lesson_id', models.PositiveIntegerField(default=0, verbose_name='Идентификатор урока')),
                ('step_id', models.PositiveIntegerField(default=0, verbose_name='Идентификатор степа')),
                ('stepik_link', models.CharField(max_length=500, verbose_name='Ссылка на страницу материала на Stepik')),
                ('material_type', models.CharField(default='text', max_length=50, verbose_name='Тип материала')),
                ('text', models.TextField(verbose_name='Текст урока')),
            ],
        ),
    ]
