# Generated by Django 3.0.3 on 2020-05-19 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_coursematerial_lesson_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursematerial',
            options={'verbose_name': 'Материал курса', 'verbose_name_plural': 'Материалы курса'},
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время создания'),
            preserve_default=False,
        ),
    ]
