# Generated by Django 3.0.3 on 2020-05-19 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200519_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.CharField(default='course_material', max_length=100, verbose_name='Тип ответа')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Текст ответа')),
                ('votes', models.PositiveIntegerField(default=1, verbose_name='Количество голосов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Comment', verbose_name='Комментарий')),
                ('course_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.CourseMaterial', verbose_name='Материал курса')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
                'ordering': ['created_at'],
            },
        ),
    ]
